name: Greetings

on:
  pull_request_target:
  issues:
  
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Event Type
        id: get_event_type
        run: echo "::set-output name=event_type::${{ github.event_name }}"
      
      - name: Get Username
        id: get_username
        run: echo "::set-output name=username::${{ github.event.sender.login }}"

      - name: Greet User
        run: |
          if [ "${{ steps.get_event_type.outputs.event_type }}" == "pull_request" ]; then
            echo "Hey ${{ steps.get_username.outputs.username }} welcome, congratulations on your first pull request in our repo🥳"
          elif [ "${{ steps.get_event_type.outputs.event_type }}" == "issues" ]; then
            echo "Hey ${{ steps.get_username.outputs.username }} welcome, congratulations on your first issue in our repo🥳"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
