name: Greetings

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Get User Information
        id: user_info
        run: |
          num_issues=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/search/issues?q=type:issue+is:open+author:${{ github.event.sender.login }}+repo:${{ github.repository }}&per_page=1" \
            | jq '.total_count')
          num_prs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/search/issues?q=type:pr+is:open+author:${{ github.event.sender.login }}+repo:${{ github.repository }}&per_page=1" \
            | jq '.total_count')
          
          echo "::set-output name=num_issues::$num_issues"
          echo "::set-output name=num_prs::$num_prs"
          
      - name: Greet User
        run: |
          num_issues="${{ steps.user_info.outputs.num_issues }}"
          num_prs="${{ steps.user_info.outputs.num_prs }}"
          echo "Hey ${{ github.event.sender.login }} welcome! You have opened $num_issues issues and created $num_prs pull requests. Keep up the good work! 🥳"
