name: Greetings

on:
  pull_request_target:
  issues:
  
jobs:
  greeting:
    runs-on: ubuntu-latest
    env:
      EVENT_TYPE: ${{ github.event_name }}
      USERNAME: ${{ github.event.sender.login }}
    steps:
      - name: Greet User
        run: |
          if [ "$EVENT_TYPE" == "pull_request" ]; then
            echo "Hey $USERNAME welcome, congratulations on your pull request🥳"
          elif [ "$EVENT_TYPE" == "issues" ]; then
            echo "Hey $USERNAME welcome, congratulations on your issue🥳"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
